export enum PageRoutes {
    HOME = '/home',
    MOVIE_LIST = '/movies',
    MOVIE_INFO = '/movie-info',
    MOVIE_INFO_ROUTE = '/movie-info/:id',
    DIRECTOR_INFO = '/director-info',
    DIRECTOR_INFO_ROUTE = '/director-info/:id',
    ACTOR_INFO = '/actor-info',
    ACTOR_INFO_ROUTE = '/actor-info/:id',
    GENRE_INFO = '/genre',
    GENRE_INFO_ROUTE = '/genre/:id',
    SEARCH_RESULT = '/search',
    LOGIN = '/login',
    REGISTER = '/register',
    USER_PROFILE = '/user',
    USER_PROFILE_ROUTE = '/user/:name',
}
